import {
  amber,
  amberDark,
  blue,
  blueDark,
  brown,
  brownDark,
  gray,
  grayDark,
  green,
  greenDark,
  pink,
  pinkDark,
  red,
  redDark,
  sand,
  sandDark,
  yellow,
  yellowDark,
} from '@radix-ui/colors'

export const COLORS = {
  light: {
    max: 'black',
    min: 'white',
    background: {
      default: gray.gray1,
      muted: gray.gray3,
      pale: gray.gray10,
    },
    text: {
      default: gray.gray12,
      boosted: 'black',
      subdued: gray.gray10,
      muted: gray.gray8,
      pale: gray.gray1,
    },
    action: {
      max: blue.blue12,
      boosted: blue.blue11,
      default: blue.blue10,
      muted: blue.blue6,
      pale: blue.blue3,
    },
    danger: {
      max: red.red12,
      boosted: red.red11,
      default: red.red10,
      muted: red.red6,
      pale: red.red3,
    },
    warning: {
      max: yellow.yellow12,
      boosted: yellow.yellow11,
      default: yellow.yellow10,
      muted: yellow.yellow6,
      pale: yellow.yellow3,
    },
    success: {
      max: green.green12,
      boosted: green.green11,
      default: green.green10,
      muted: green.green6,
      pale: green.green3,
    },
    neutral: {
      max: sand.sand12,
      boosted: sand.sand11,
      default: sand.sand10,
      muted: sand.sand6,
      pale: sand.sand3,
    },
    pastel1: {
      default: blue.blue10,
      boosted: blue.blue11,
      max: blue.blue12,
      muted: blue.blue6,
    },
    pastel2: {
      default: pink.pink10,
      boosted: pink.pink11,
      max: pink.pink12,
      muted: pink.pink6,
    },
    pastel3: {
      default: green.green10,
      boosted: green.green11,
      max: green.green12,
      muted: green.green6,
    },
    pastel4: {
      default: amber.amber10,
      boosted: amber.amber11,
      max: amber.amber12,
      muted: amber.amber6,
    },
    pastel5: {
      default: brown.brown10,
      boosted: brown.brown11,
      max: brown.brown12,
      muted: brown.brown6,
    },
  },
  dark: {
    max: 'white',
    min: 'black',
    background: {
      default: grayDark.gray1,
      muted: grayDark.gray3,
      pale: grayDark.gray10,
    },
    text: {
      default: grayDark.gray12,
      boosted: 'white',
      subdued: grayDark.gray10,
      muted: grayDark.gray8,
      pale: grayDark.gray1,
    },
    action: {
      max: blueDark.blue12,
      boosted: blueDark.blue11,
      default: blueDark.blue10,
      muted: blueDark.blue6,
      pale: blueDark.blue3,
    },
    danger: {
      max: redDark.red12,
      boosted: redDark.red11,
      default: redDark.red10,
      muted: redDark.red6,
      pale: redDark.red3,
    },
    warning: {
      max: yellowDark.yellow12,
      boosted: yellowDark.yellow11,
      default: yellowDark.yellow10,
      muted: yellowDark.yellow6,
      pale: yellowDark.yellow3,
    },
    success: {
      max: greenDark.green12,
      boosted: greenDark.green11,
      default: greenDark.green10,
      muted: greenDark.green6,
      pale: greenDark.green3,
    },
    neutral: {
      max: sandDark.sand12,
      boosted: sandDark.sand11,
      default: sandDark.sand10,
      muted: sandDark.sand6,
      pale: sandDark.sand3,
    },
    pastel1: {
      default: blueDark.blue10,
      boosted: blueDark.blue11,
      max: blueDark.blue12,
      muted: blueDark.blue6,
    },
    pastel2: {
      default: pinkDark.pink10,
      boosted: pinkDark.pink11,
      max: pinkDark.pink12,
      muted: pinkDark.pink6,
    },
    pastel3: {
      default: greenDark.green10,
      boosted: greenDark.green11,
      max: greenDark.green12,
      muted: greenDark.green6,
    },
    pastel4: {
      default: amberDark.amber10,
      boosted: amberDark.amber11,
      max: amberDark.amber12,
      muted: amberDark.amber6,
    },
    pastel5: {
      default: brownDark.brown10,
      boosted: brownDark.brown11,
      max: brownDark.brown12,
      muted: brownDark.brown6,
    },
  },
} as const
